name: example
description: Example Application using simple_json_persistence
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
dependencies:
  logging: ^1.3.0
  logging_appenders:
    path: ../
dev_dependencies:
  lints: ^6.0.0
